spring:
  application:
    name: spring-gemini-ai

  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: AIzaSyAbx87XrYbXEE7LNvCM7d2RQd9bSPjWoJI
        chat:
          options:
            response-mime-type: application/json

server:
  port: 9191
