spring:
  application:
    name: spring-gemini-ai

  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key:
        chat:
          options:
            response-mime-type: application/json

server:
  port: 9191
